application: cornerstores-in
version: 1
runtime: python27
threadsafe: true
api_version: 1


handlers:
- url: /css
  mime_type: text/css
  static_dir: css

- url: /js
  mime_type: text/javascript
  static_dir: js


- url: /signup
  script: main.app


- url: /login
  script: main.app


- url: /forgot
  script: main.app


- url: .*
  script: main.app



libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"